# Generated by Django 5.2.1 on 2025-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="experience",
            field=models.IntegerField(null=True),
        ),
    ]
